# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
  email:
    - derhansen@gmail.com

before_script:
    - composer self-update
    - composer install --dev --no-interaction --prefer-source